# Generated by Django 4.1.7 on 2023-07-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_impressions_impression'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impressions',
            options={'ordering': ['created']},
        ),
        migrations.AlterField(
            model_name='impressions',
            name='star',
            field=models.PositiveIntegerField(choices=[(1, '✨'), (2, '✨✨'), (3, '✨✨✨'), (4, '✨✨✨✨'), (5, '✨✨✨✨✨')]),
        ),
    ]
