# Generated by Django 4.1.7 on 2023-07-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_impressions_options_alter_impressions_star'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impressions',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='impressions',
            name='accept',
            field=models.BooleanField(default=True),
        ),
    ]
