# Generated by Django 4.1.7 on 2023-07-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_impressions_options_impressions_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='impressions',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
