# Generated by Django 4.1.7 on 2023-07-09 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_impressions_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('host_pwd', models.CharField(max_length=200)),
                ('host_email', models.EmailField(max_length=200)),
                ('admin_username', models.CharField(max_length=200)),
                ('admin_password', models.CharField(max_length=200)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('website', models.URLField()),
                ('cost', models.IntegerField()),
                ('income', models.IntegerField()),
            ],
        ),
    ]
