# Generated by Django 4.1.7 on 2023-07-09 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_customers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='customers',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
