# Generated by Django 4.1.7 on 2023-07-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_contact_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='pack1',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack1'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack10',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack10'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack11',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack11'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack12',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack12'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack2',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack2'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack3',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack3'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack5',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack5'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack6',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack6'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack7',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack7'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack8',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack8'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='pack9',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pack9'),
        ),
    ]
