# Generated by Django 4.1.7 on 2023-07-09 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_offer_pack1_alter_offer_pack10_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='pack5',
        ),
    ]
